services:
  chatgpt-api:
    image: chatgptapi:dev
    container_name: "ChatGPT-Api"
    build:
      args:
        LAUNCHING_FROM_VS: true
        BUILD_CONFIGURATION: Debug
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "ChatGPT-Api"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      - NUGET_FALLBACK_PACKAGES=
    volumes:
      - C:\Users\shahzab.akhtar\Desktop\ChatGPT-Api\ChatGPT-Api:/app:rw
      - C:\Users\shahzab.akhtar\Desktop\ChatGPT-Api:/src:rw
      - C:\Users\shahzab.akhtar\vsdbg\vs2017u5:/remote_debugger:rw
      - C:\Users\shahzab.akhtar\.nuget\packages:/.nuget/packages:ro
      - C:\Users\shahzab.akhtar\AppData\Roaming\ASP.NET\Https:/root/.aspnet/https:ro
      - C:\Users\shahzab.akhtar\AppData\Roaming\ASP.NET\Https:/home/app/.aspnet/https:ro
      - C:\Users\shahzab.akhtar\AppData\Roaming\Microsoft\UserSecrets:/root/.microsoft/usersecrets:ro
      - C:\Users\shahzab.akhtar\AppData\Roaming\Microsoft\UserSecrets:/home/app/.microsoft/usersecrets:ro
      - C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Sdks\Microsoft.Docker.Sdk\tools\linux-x64\net8.0:/VSTools:ro
      - C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\CommonExtensions\Microsoft\HotReload:/HotReloadAgent:ro

    entrypoint: "dotnet --roll-forward Major /VSTools/DistrolessHelper/DistrolessHelper.dll --wait"
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      com.microsoft.visualstudio.debuggee.arguments: " --additionalProbingPath /.nuget/packages  \"/app/bin/Debug/net8.0/ChatGPT-Api.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "dotnet --roll-forward Major /VSTools/DistrolessHelper/DistrolessHelper.dll --stop dotnet"
    tty: true
  chatgpt_consumer_api:
    image: chatgptconsumerapi:dev
    container_name: "ChatGPT_Consumer_Api"
    build:
      args:
        LAUNCHING_FROM_VS: true
        BUILD_CONFIGURATION: Debug
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "ChatGPT_Consumer_Api"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      - NUGET_FALLBACK_PACKAGES=
    volumes:
      - C:\Users\shahzab.akhtar\Desktop\ChatGPT-Api\ChatGPT_Consumer_Api:/app:rw
      - C:\Users\shahzab.akhtar\Desktop\ChatGPT-Api\ChatGPT_Consumer_Api:/src:rw
      - C:\Users\shahzab.akhtar\vsdbg\vs2017u5:/remote_debugger:rw
      - C:\Users\shahzab.akhtar\.nuget\packages:/.nuget/packages:ro
      - C:\Users\shahzab.akhtar\AppData\Roaming\ASP.NET\Https:/root/.aspnet/https:ro
      - C:\Users\shahzab.akhtar\AppData\Roaming\ASP.NET\Https:/home/app/.aspnet/https:ro
      - C:\Users\shahzab.akhtar\AppData\Roaming\Microsoft\UserSecrets:/root/.microsoft/usersecrets:ro
      - C:\Users\shahzab.akhtar\AppData\Roaming\Microsoft\UserSecrets:/home/app/.microsoft/usersecrets:ro
      - C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Sdks\Microsoft.Docker.Sdk\tools\linux-x64\net8.0:/VSTools:ro
      - C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\CommonExtensions\Microsoft\HotReload:/HotReloadAgent:ro

    entrypoint: "dotnet --roll-forward Major /VSTools/DistrolessHelper/DistrolessHelper.dll --wait"
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      com.microsoft.visualstudio.debuggee.arguments: " --additionalProbingPath /.nuget/packages  \"/app/bin/Debug/net8.0/ChatGPT_Consumer_Api.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "dotnet --roll-forward Major /VSTools/DistrolessHelper/DistrolessHelper.dll --stop dotnet"
    tty: true
